/**
 * tests/unit/model-router-parity.test.ts (vitest)
 *
 * Byte parity: buildRouterState output must equal the reference Python
 * sidecar's state_from_body output for every fixture case. The fixture
 * (scripts/laya-reference/parity-fixture.json) is generated by
 * scripts/laya-reference/gen-parity-fixture.py, which extracts
 * state_from_body VERBATIM from the reference sidecar
 * (scripts/laya-reference/laya-router.py, HEAD e6fdc10) and runs it.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import { buildRouterState } from "@/sse/services/modelRouterTier";

const here = path.dirname(fileURLToPath(import.meta.url));
const fixturePath = path.resolve(here, "../../scripts/laya-reference/parity-fixture.json");
const fixture: Array<{ body: unknown; state: string }> = JSON.parse(
  readFileSync(fixturePath, "utf8")
);

describe("buildRouterState byte parity with the sidecar state_from_body", () => {
  it("fixture has at least 30 cases", () => {
    expect(fixture.length).toBeGreaterThanOrEqual(30);
  });

  for (let i = 0; i < fixture.length; i += 1) {
    it(`case ${i + 1} byte-equal`, () => {
      const got = buildRouterState(fixture[i].body as Parameters<typeof buildRouterState>[0]);
      expect(got).toBe(fixture[i].state);
    });
  }
});
